In [1]:
import sklearn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:

data = pd.read_csv('D:\heart disease prediction\ACC_minute.csv')
data.head()

<>:1: SyntaxWarning: invalid escape sequence '\h'
<>:1: SyntaxWarning: invalid escape sequence '\h'
C:\Users\harsh\AppData\Local\Temp\ipykernel_31612\3272207122.py:1: SyntaxWarning: invalid escape sequence '\h'
  data = pd.read_csv('D:\heart disease prediction\ACC_minute.csv')

                  date     open     high      low    close  volume
0  2015-02-02 09:15:00  1554.90  1556.70  1544.80  1549.60    1441
1  2015-02-02 09:16:00  1550.70  1551.30  1546.50  1548.30     424
2  2015-02-02 09:17:00  1548.35  1549.00  1545.15  1547.55     831
3  2015-02-02 09:18:00  1547.55  1547.55  1543.00  1544.20    1297
4  2015-02-02 09:19:00  1544.25  1547.75  1544.25  1547.75     255

In [3]:
data.describe()

,open,high,low,close,volume
count,969525.000000,969525.000000,969525.000000,969525.000000,969525.000000
mean,1780.826449,1781.797871,1779.831387,1780.817680,1602.330279
std,390.241622,390.457589,390.003962,390.239132,4856.557515
min,896.000000,899.100000,895.150000,896.500000,0.000000
25%,1470.350000,1471.050000,1469.900000,1470.350000,226.000000
50%,1683.000000,1684.000000,1682.100000,1683.000000,625.000000
75%,2054.350000,2055.700000,2053.100000,2054.350000,1603.000000
max,2841.300000,2844.000000,2837.000000,2842.400000,962709.000000

In [4]:
x = data['high']
y = data['low']

In [5]:
x_train,x_test,y_train,y_test = train_test_split(
    x,y, test_size=30, random_state=42
)

In [6]:
model = LogisticRegression(max_iter=100_000)
model.fit(x_train,y_train)

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([ 72.,  72.,  72., 200.,  72.,  72., 200., 200.,  72., 200.,  72.,
        72.,  72., 200.,  72., 200., 200., 200., 200., 200., 200.,  72.,
        72., 200., 200., 200., 200., 200.,  72.,  72.])

In [ ]:
print(accuracy_score(y_test,y_pred)) #probablity

0.0